### ISSUE TITLE
more detailed codes and instructions

### ISSUE THREAD

**Issue by Yanxing-Shi** [ArayCHN/MSC_robot_manipulation#16]
Your work is excellent, but I can't understand your code framework. Could you please give me a detailed description? I want to know more detailed codes and instructions.Thank you very much!

**Comment by kpaonaut** [comment]
Hi,
Thanks for your interest in this repo.

**Please star a repo as an acknowledgement if it is/has been helpful to you.**

Unfortunately, I'm afraid the code is unreproducible on your own PC, due to the large amount of hardware and libraries you'll have to set up. (including the actual robots.)

However, if you are interested in the code itself (without seeing it work on actual robots), take a look at the code from
`https://github.com/ArayCHN/MSC_robot_manipulation/blob/master/WangRui/TSCPD_straightening/TS_CPD.m`. What this file does is the "rope straightening" experiment as described in our paper (read it first!). From that file, you could jump to different functions and see their implementations.

Above all, I would suggest you read our paper on [arxiv](https://arxiv.org/abs/1810.04077) first before anything. Otherwise it is unlikely that you can understand the code (when you are not familiar or fully aware of the algorithm itself).
